import type { ProblemItem, ScreeningInstrument } from './types'

export const mockProblems: ProblemItem[] = [
  // === Conditions (6) ===
  {
    id: 'cond-1',
    category: 'condition',
    description: 'Type 2 Diabetes Mellitus',
    icdCode: 'E11.9',
    snomedCode: '44054006',
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'diagnosed',
    sourceDate: '03/15/22',
    severity: 'moderate',
    onsetDate: '03/15/22',
    history: [
      { id: 'evt-1a', type: 'marked-active', performedBy: 'Jess Okafor, PA-C', performedAt: '03/15/22, 10:15a PT' },
      { id: 'evt-1b', type: 'confirmed', performedBy: 'Jess Okafor, PA-C', performedAt: '03/15/22, 10:14a PT' },
      { id: 'evt-1c', type: 'imported', performedBy: 'System — CCDA Import', performedAt: '03/15/22, 9:00a PT' },
    ],
  },
  {
    id: 'cond-2',
    category: 'condition',
    description: 'Essential Hypertension',
    icdCode: 'I10',
    snomedCode: '59621000',
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'diagnosed',
    sourceDate: '01/08/20',
    onsetDate: '01/08/20',
    history: [
      { id: 'evt-2a', type: 'marked-active', performedBy: 'Dr. Priya Sharma, MD', performedAt: '01/08/20, 2:30p PT' },
      { id: 'evt-2b', type: 'confirmed', performedBy: 'Dr. Priya Sharma, MD', performedAt: '01/08/20, 2:29p PT' },
      { id: 'evt-2c', type: 'reported', performedBy: 'Patient', performedAt: '01/08/20, 10:00a PT' },
    ],
  },
  {
    id: 'cond-3',
    category: 'condition',
    description: 'Chronic Low Back Pain',
    icdCode: 'M54.5',
    snomedCode: '278860009',
    verificationStatus: 'unconfirmed',
    clinicalStatus: 'active',
    source: 'reported',
    sourceDate: '11/20/25',
    history: [
      { id: 'evt-3a', type: 'reported', performedBy: 'Patient', performedAt: '11/20/25, 9:45a PT' },
    ],
  },
  {
    id: 'cond-4',
    category: 'condition',
    description: 'Asthma, Mild Persistent',
    icdCode: 'J45.30',
    snomedCode: '195967001',
    verificationStatus: 'confirmed',
    clinicalStatus: 'recurrence',
    source: 'diagnosed',
    sourceDate: '02/01/26',
    onsetDate: '06/02/18',
    history: [
      { id: 'evt-4a', type: 'recurrence', performedBy: 'Dr. Tanaka, MD', performedAt: '02/01/26, 2:30p PT' },
      { id: 'evt-4b', type: 'marked-inactive', performedBy: 'Dr. Priya Sharma, MD', performedAt: '09/15/23, 3:00p PT' },
      { id: 'evt-4f', type: 'marked-resolved' as const, performedBy: 'Dr. Priya Sharma, MD', performedAt: '09/15/23, 2:55p PT', effectiveDate: '09/15/23', deletedAt: '09/16/23, 9:00a PT', deletedBy: 'Dr. Priya Sharma, MD', deletionReason: 'entered-in-error' as const },
      { id: 'evt-4c', type: 'marked-active', performedBy: 'Dr. Priya Sharma, MD', performedAt: '06/02/18, 11:15a PT' },
      { id: 'evt-4d', type: 'confirmed', performedBy: 'Dr. Priya Sharma, MD', performedAt: '06/02/18, 11:14a PT' },
      { id: 'evt-4e', type: 'imported', performedBy: 'System — CCDA Import', performedAt: '06/02/18, 8:00a PT' },
    ],
  },
  {
    id: 'cond-5',
    category: 'condition',
    description: 'Hypothyroidism, Unspecified',
    icdCode: 'E03.9',
    snomedCode: '40930008',
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'imported',
    sourceDate: '09/14/24',
    onsetDate: '09/14/24',
    history: [
      { id: 'evt-5a', type: 'marked-active', performedBy: 'Marco Rivera, PA-C', performedAt: '09/14/24, 10:30a PT' },
      { id: 'evt-5b', type: 'confirmed', performedBy: 'Marco Rivera, PA-C', performedAt: '09/14/24, 10:29a PT' },
      { id: 'evt-5c', type: 'imported', performedBy: 'System — CCDA Import', performedAt: '09/14/24, 9:00a PT' },
    ],
  },
  {
    id: 'cond-6',
    category: 'condition',
    description: 'Obesity, BMI 30.0-34.9',
    icdCode: 'E66.01',
    snomedCode: '408512008',
    verificationStatus: 'unconfirmed',
    clinicalStatus: 'active',
    source: 'reported',
    sourceDate: '02/28/26',
    history: [
      { id: 'evt-6a', type: 'reported', performedBy: 'Patient', performedAt: '02/28/26, 10:05a PT' },
    ],
  },

  // === Encounter Dx (3) ===
  {
    id: 'enc-1',
    category: 'encounter-dx',
    description: 'Acute Sinusitis, Unspecified',
    icdCode: 'J01.90',
    snomedCode: '15805002',
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'diagnosed',
    sourceDate: '03/09/26',
    onsetDate: '03/09/26',
    history: [
      { id: 'evt-7a', type: 'marked-active', performedBy: 'Marco Rivera, PA-C', performedAt: '03/09/26, 10:45a PT', encounterVisitName: 'Sore Throat' },
      { id: 'evt-7b', type: 'confirmed', performedBy: 'Marco Rivera, PA-C', performedAt: '03/09/26, 10:44a PT', encounterVisitName: 'Sore Throat' },
    ],
  },
  {
    id: 'enc-2',
    category: 'encounter-dx',
    description: 'Urinary Tract Infection, Site Not Specified',
    icdCode: 'N39.0',
    snomedCode: '68566005',
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'diagnosed',
    sourceDate: '01/15/26',
    onsetDate: '01/15/26',
    history: [
      { id: 'evt-8a', type: 'marked-active', performedBy: 'Dr. Tanaka, MD', performedAt: '01/15/26, 2:15p PT', encounterVisitName: 'Urinary Tract Infection' },
      { id: 'evt-8b', type: 'confirmed', performedBy: 'Dr. Tanaka, MD', performedAt: '01/15/26, 2:14p PT', encounterVisitName: 'Urinary Tract Infection' },
      { id: 'evt-8c', type: 'reported', performedBy: 'Patient', performedAt: '01/15/26, 1:00p PT', encounterVisitName: 'Urinary Tract Infection' },
    ],
  },
  {
    id: 'enc-3',
    category: 'encounter-dx',
    description: 'Vitamin D Deficiency',
    icdCode: 'E55.9',
    snomedCode: '34713006',
    verificationStatus: 'unconfirmed',
    clinicalStatus: 'active',
    source: 'reported',
    sourceDate: '03/09/26',
    history: [
      { id: 'evt-9a', type: 'reported', performedBy: 'Marco Rivera, PA-C', performedAt: '03/09/26, 10:35a PT', encounterVisitName: 'Annual Wellness Visit' },
    ],
  },

  // === SDOH (3) ===
  {
    id: 'sdoh-1',
    category: 'sdoh',
    description: 'Food Insecurity',
    icdCode: 'Z59.48',
    snomedCode: '733423003',
    verificationStatus: 'unconfirmed',
    clinicalStatus: 'active',
    source: 'screened',
    sourceDate: '02/10/26',
    relatedScreeningId: 'si-1',
    history: [
      { id: 'evt-10a', type: 'screening-detected', performedBy: 'System — AHC HRSN Screening', performedAt: '02/10/26, 10:30a PT' },
    ],
  },
  {
    id: 'sdoh-2',
    category: 'sdoh',
    description: 'Transportation Insecurity',
    icdCode: 'Z59.82',
    snomedCode: '551411000124101',
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'screened',
    sourceDate: '02/10/26',
    relatedScreeningId: 'si-1',
    history: [
      { id: 'evt-11a', type: 'marked-active', performedBy: 'Marco Rivera, PA-C', performedAt: '02/10/26, 11:00a PT' },
      { id: 'evt-11b', type: 'confirmed', performedBy: 'Marco Rivera, PA-C', performedAt: '02/10/26, 10:59a PT' },
      { id: 'evt-11c', type: 'screening-detected', performedBy: 'System — AHC HRSN Screening', performedAt: '02/10/26, 10:30a PT' },
    ],
  },
  {
    id: 'sdoh-3',
    category: 'sdoh',
    description: 'Financial Strain',
    icdCode: 'Z59.86',
    snomedCode: '454061000124102',
    verificationStatus: 'unconfirmed',
    clinicalStatus: 'active',
    source: 'screened',
    sourceDate: '02/10/26',
    relatedScreeningId: 'si-2',
    history: [
      { id: 'evt-12a', type: 'screening-detected', performedBy: 'System — PRAPARE Screening', performedAt: '02/10/26, 10:30a PT' },
    ],
  },

  // === Health Concerns (3) ===
  {
    id: 'hc-1',
    category: 'health-concern',
    description: 'Weight Management Goal',
    icdCode: null,
    snomedCode: null,
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'reported',
    sourceDate: '01/05/26',
    history: [
      { id: 'evt-13a', type: 'marked-active', performedBy: 'Marco Rivera, PA-C', performedAt: '01/05/26, 11:10a PT' },
      { id: 'evt-13b', type: 'confirmed', performedBy: 'Marco Rivera, PA-C', performedAt: '01/05/26, 11:09a PT' },
      { id: 'evt-13c', type: 'reported', performedBy: 'Patient', performedAt: '01/05/26, 10:00a PT' },
    ],
  },
  {
    id: 'hc-2',
    category: 'health-concern',
    description: 'Smoking Cessation',
    icdCode: null,
    snomedCode: null,
    verificationStatus: 'unconfirmed',
    clinicalStatus: 'active',
    source: 'reported',
    sourceDate: '12/12/25',
    history: [
      { id: 'evt-14a', type: 'reported', performedBy: 'Patient', performedAt: '12/12/25, 9:30a PT' },
    ],
  },
  {
    id: 'hc-3',
    category: 'health-concern',
    description: 'Anxiety',
    icdCode: null,
    snomedCode: null,
    verificationStatus: 'confirmed',
    clinicalStatus: 'resolved',
    source: 'reported',
    sourceDate: '08/20/24',
    abatementDate: '11/30/25',
    history: [
      { id: 'evt-15a', type: 'marked-resolved', performedBy: 'Dr. Priya Sharma, MD', performedAt: '11/30/25, 4:00p PT' },
      { id: 'evt-15b', type: 'marked-active', performedBy: 'Dr. Priya Sharma, MD', performedAt: '08/20/24, 2:15p PT' },
      { id: 'evt-15c', type: 'confirmed', performedBy: 'Dr. Priya Sharma, MD', performedAt: '08/20/24, 2:14p PT' },
      { id: 'evt-15d', type: 'reported', performedBy: 'Patient', performedAt: '08/20/24, 1:00p PT' },
    ],
  },
]

export const screeningInstruments: ScreeningInstrument[] = [
  {
    id: 'si-1',
    name: 'AHC HRSN Screening Tool',
    abbreviation: 'AHC HRSN',
    administeredDate: '02/10/26',
    score: '3 needs identified',
    interpretation: 'Social needs detected',
  },
  {
    id: 'si-2',
    name: 'PRAPARE',
    abbreviation: 'PRAPARE',
    administeredDate: '02/10/26',
    score: '4/10',
    interpretation: 'Moderate risk',
  },
]
