import type { ProblemItem, ScreeningInstrument } from './types'

export const mockProblems: ProblemItem[] = [
  // === Conditions (6) ===
  {
    id: 'cond-1',
    category: 'condition',
    description: 'Type 2 Diabetes Mellitus',
    icdCode: 'E11.9',
    snomedCode: '44054006',
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'diagnosed',
    sourceDate: '03/15/22',
    severity: 'moderate',
  },
  {
    id: 'cond-2',
    category: 'condition',
    description: 'Essential Hypertension',
    icdCode: 'I10',
    snomedCode: '59621000',
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'diagnosed',
    sourceDate: '01/08/20',
  },
  {
    id: 'cond-3',
    category: 'condition',
    description: 'Chronic Low Back Pain',
    icdCode: 'M54.5',
    snomedCode: '278860009',
    verificationStatus: 'unconfirmed',
    clinicalStatus: 'active',
    source: 'reported',
    sourceDate: '11/20/25',
  },
  {
    id: 'cond-4',
    category: 'condition',
    description: 'Asthma, Mild Persistent',
    icdCode: 'J45.30',
    snomedCode: '195967001',
    verificationStatus: 'confirmed',
    clinicalStatus: 'inactive',
    source: 'diagnosed',
    sourceDate: '06/02/18',
    resolvedDate: '09/15/23',
  },
  {
    id: 'cond-5',
    category: 'condition',
    description: 'Hypothyroidism, Unspecified',
    icdCode: 'E03.9',
    snomedCode: '40930008',
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'imported',
    sourceDate: '09/14/24',
  },
  {
    id: 'cond-6',
    category: 'condition',
    description: 'Obesity, BMI 30.0-34.9',
    icdCode: 'E66.01',
    snomedCode: '408512008',
    verificationStatus: 'unconfirmed',
    clinicalStatus: 'active',
    source: 'reported',
    sourceDate: '02/28/26',
  },

  // === Encounter Dx (3) ===
  {
    id: 'enc-1',
    category: 'encounter-dx',
    description: 'Acute Sinusitis, Unspecified',
    icdCode: 'J01.90',
    snomedCode: '15805002',
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'diagnosed',
    sourceDate: '03/09/26',
  },
  {
    id: 'enc-2',
    category: 'encounter-dx',
    description: 'Urinary Tract Infection, Site Not Specified',
    icdCode: 'N39.0',
    snomedCode: '68566005',
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'diagnosed',
    sourceDate: '01/15/26',
  },
  {
    id: 'enc-3',
    category: 'encounter-dx',
    description: 'Vitamin D Deficiency',
    icdCode: 'E55.9',
    snomedCode: '34713006',
    verificationStatus: 'unconfirmed',
    clinicalStatus: 'active',
    source: 'reported',
    sourceDate: '03/09/26',
  },

  // === SDOH (3) ===
  {
    id: 'sdoh-1',
    category: 'sdoh',
    description: 'Food Insecurity',
    icdCode: 'Z59.48',
    snomedCode: '733423003',
    verificationStatus: 'unconfirmed',
    clinicalStatus: 'active',
    source: 'screened',
    sourceDate: '02/10/26',
  },
  {
    id: 'sdoh-2',
    category: 'sdoh',
    description: 'Transportation Insecurity',
    icdCode: 'Z59.82',
    snomedCode: '551411000124101',
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'screened',
    sourceDate: '02/10/26',
  },
  {
    id: 'sdoh-3',
    category: 'sdoh',
    description: 'Financial Strain',
    icdCode: 'Z59.86',
    snomedCode: '454061000124102',
    verificationStatus: 'unconfirmed',
    clinicalStatus: 'active',
    source: 'screened',
    sourceDate: '02/10/26',
  },

  // === Health Concerns (3) ===
  {
    id: 'hc-1',
    category: 'health-concern',
    description: 'Weight Management Goal',
    icdCode: null,
    snomedCode: null,
    verificationStatus: 'confirmed',
    clinicalStatus: 'active',
    source: 'reported',
    sourceDate: '01/05/26',
  },
  {
    id: 'hc-2',
    category: 'health-concern',
    description: 'Smoking Cessation',
    icdCode: null,
    snomedCode: null,
    verificationStatus: 'unconfirmed',
    clinicalStatus: 'active',
    source: 'reported',
    sourceDate: '12/12/25',
  },
  {
    id: 'hc-3',
    category: 'health-concern',
    description: 'Anxiety',
    icdCode: null,
    snomedCode: null,
    verificationStatus: 'confirmed',
    clinicalStatus: 'resolved',
    source: 'reported',
    sourceDate: '08/20/24',
    resolvedDate: '11/30/25',
  },
]

export const screeningInstruments: ScreeningInstrument[] = [
  { id: 'si-1', name: 'AHC HRSN Screening Tool', abbreviation: 'AHC-HRSN' },
  { id: 'si-2', name: 'PRAPARE', abbreviation: 'PRAPARE' },
]
